### PR TITLE
change submit logic and build lastPage and reedirection

### PR DESCRIPTION
**Pull request by SarahWett**
**What's new:**

- created a "Saved!"-Page to give visual Feedback after submit
- created redirection to home screen after 3000 ms 
- built button component to replace button with changing type by page 

[US 5](https://github.com/SarahWett/capstone-project/issues/4)

### CODE REVIEW

**Comment by bk1405bgl** [comment]
Form/index.js
Line 154
<Navbar />
my be <Navbar> is not a self closing tag because you close it in line 204

**Comment by SarahWett** [comment]
> Form/index.js
> Line 154
> `<Navbar />`
> my be `<Navbar>` is not a self closing tag because you close it in line 204

This may be confusing because of the red & green lines of changed files but the Navbar is part of this one here:
```
 {showSavedPage ? (
        <>
          <div>
            <StyledSavedText>Saved!</StyledSavedText>
          </div>
          <Navbar />
        </>
      ) : (
        <>
          <StyledForm onSubmit={handleSubmit}>
            <StyledProgressBar>
              <StyledProgress
                style={{
                  width: page === 0 ? "33.3%" : page === 1 ? "66.6%" : "100%",
                }}
              >
```
So this should be correct :) 
It's part of a page only shown when handleSubmit is fired.

**Review by SarahWett — COMMENTED** [review]
For some reason the radio button  clicked in the last session is always logged when none is selected. 
It also didn't work out to require the input in different ways as using a seperate hook so I tried this one, which is also not working out properly.

**Review by SarahWett — COMMENTED** [review]
QuestionTwo: Finally reduced states to useLocalStorageState in Form.js

**Pull request merged**
